name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Validate Docker Compose files
        run: |
          for file in compose/*.yaml; do
            echo "Validating $file..."
            docker-compose -f $file config > /dev/null
          done
      
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: compose/*.yaml
          config_file: .yamllint.yml
